name: uyobuyo_client
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  # UI
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  flutter_bounce: ^1.1.0
  yandex_mapkit: ^3.3.3


  # Helpers
  dartz: ^0.10.1
  intl: any
  mask_text_input_formatter: ^2.5.0
  freezed_annotation: ^2.4.1
  sms_autofill: ^2.3.0
  pin_code_fields: ^8.0.1
  geolocator: ^10.1.0
  image_picker: ^1.0.4

  # Local storage
  shared_preferences: ^2.1.1

  # Networking
  dio: ^5.3.3
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.1.14

  # State management
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  provider: ^6.0.5

  # Navigation
  go_router: ^11.0.0


  # Firebase
  firebase_core: ^2.16.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.2
  flutter_lints: ^2.0.3


flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
